chore: use confluent kafka image for tests (#289)
Replace `docker.redpanda.com/redpandadata/redpanda` for
`confluentinc/confluent-local` docker image for Kafka tests.

The sarama tests are currently flaking with the following error:

```
    ibm_sarama.go:127: 
        	Error Trace:	/home/runner/work/orchestrion/orchestrion/_integration-tests/tests/ibm_sarama/ibm_sarama.go:87
        	            				/home/runner/work/orchestrion/orchestrion/_integration-tests/tests/ibm_sarama/ibm_sarama.go:127
        	            				/home/runner/work/orchestrion/orchestrion/_integration-tests/utils/suite.go:77
        	            				/home/runner/work/orchestrion/orchestrion/_integration-tests/tests/ibm_sarama/gen_test.go:18
        	Error:      	Received unexpected error:
        	            	kafka: client has run out of available brokers to talk to: kafka: error decoding packet: message of length 1213486160 too large or too small
        	Test:       	TestIntegration_ibm_sarama
        	Messages:   	failed to create producer
```

We suspect it might be caused by the test starting before the container
being fully ready. The confluent kafka testcontainers module seems to
have smarter [readiness check
logic](https://github.com/testcontainers/testcontainers-go/blob/main/modules/kafka/kafka.go#L71-L89)
than the
[redpanda](https://github.com/testcontainers/testcontainers-go/blob/main/modules/redpanda/redpanda.go#L89-L95)
one, so hopefully this change solves the issue.